name: cicd_test

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu_latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: build oremi test
      run: pip install -r requirements.txt

    - name: deploy final stage
      run: python app.py prod
